---
- name: OpenSuse
  zypper:
   name:
    - apache2
    - gcc
    - glibc
    - gd
    - perl
    - php7
    - apache2-mod_php7
    - unzip
   state: latest

- name: Enable php7
  shell: 'a2enmod php7'

- name: nagios group
  group:
   name: nagios
   state: present

- name: nagios group
  group:
   name: nagcmd
   state: present

- name: nagios group
  group:
   name: nagadmin
   state: present

- name: Nagios User
  user:
   name: nagios
   comment: nagios user
   group: nagadmin

- name: wwwrun user group
  user:
   name: wwwrun
   group: nagadmin
   append: yes

- name: directory
  file:
   path: /downloads
   state: directory

- name: downloading nagios
  get_url:
   url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
   dest: /downloads

- name: Extracting Nagios Core
  unarchive:
   src: /downloads/nagios-4.2.1.tar.gz
   dest: /downloads
   remote_src: yes

- name: Virtual Host Directory
  file:
   path: /etc/httpd/conf.d
   state: directory

- name: Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
   chdir: /downloads/nagios-4.2.1

- name: init script installation
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-init

- name: config files
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-config

- name: set permissions
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-commandmode

- name: nagios web interface
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-webconf

- name: pip for htpasswd
  zypper:
   name: python3-pip
   state: latest

- name: htpasswd
  pip:
   name: passlib
   state: latest

- name: nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ nagadmin_pass }}'

- name: Restarting Apache
  service:
   name: apache2
   state: reloaded

# tasks file for roles/opensuse/snagios
