---
- name: FTP on centos
  yum:
   name: vsftpd
   state: latest
   update_cache: yes

- name: FTP server
  service:
   name: vsftpd
   state: started
   enabled: yes

- name: ftp user
  user:
   name: '{{ user }}'
   password: '{{ ftp_pass }}'

- name: access ssh
  lineinfile:
   path: /etc/ssh/sshd_config
   line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: sshd service
  service:
   name: sshd
   state: restarted
  when: successfully_denied.changed

- name: configuration file
  copy:
   src: /etc/vsftpd/vsftpd.conf
   dest: /etc/vsftpd/vsftpd.conf.default
   remote_src: True
 
- name: Limit FTP users
  replace:
   path: /etc/vsftpd/vsftpd.conf
   regexp: '#chroot_local_user=YES'
   replace: 'chroot_local_user=YES'

- name: ftp file configuration
  lineinfile:
   path: /etc/vsftpd/vsftpd.conf
   line: '{{ ftp_config }}'

- name: Vsftpd
  service:
   name: vsftpd
   state: restarted
# tasks file for roles/centos/ftp