---
- name: centos installation
  yum:
   name:
    - httpd
    - gcc
    - glibc
    - glibc-common
    - gd-devel
    - perl
    - postfix
    - unzip
   state: latest
   update_cache: yes

- name: httpd
  service:
   name: httpd
   state: started

- name: nagios group
  group:
   name: nagios
   state: present

- name: nagios group
  group:
   name: nagcmd
   state: present

- name: nagios User
  user:
   name: nagios
   shell: /bin/bash
   comment: nagios user
   group: nagios
   password: '{{ naguser_pass }}'

- name: httpd to nagios group
  user:
   name: apache
   groups: nagios
   append: yes

- name: Adding nagios user group
  user:
   name: nagios
   group: nagcmd
   append: yes

- name: www-data user group
  user:
   name: www-data
   group: nagcmd
   append: yes

- name: directory
  file:
   path: /downloads
   state: directory

- name: Downloading Nagios
  get_url:
   url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
   dest: /downloads

- name: Extracting Nagios Core
  unarchive:
   src: /downloads/nagios-4.2.1.tar.gz
   dest: /downloads
   remote_src: yes

- name: Virtual Host Directory
  file:
   path: /etc/httpd/conf.d
   state: directory

- name: Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
   chdir: /downloads/nagios-4.2.1

- name: Nagios Core
  make:
   chdir: /downloads/nagios-4.2.1
   target: all

- name: binaries installation
  make:
   chdir: /downloads/nagios-4.2.1
   target: install

- name: init script installation
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-daemoninit

- name: config files
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-config

- name: set permissions
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-commandmode

- name: Nagios web interface
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-webconf

- name: Exfolation themne
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-exfoliation

- name: classicui themne
  make:
   chdir: /downloads/nagios-4.2.1
   target: install-classicui


- name: pip installation
  yum:
   name: python3-pip
   state: latest
   update_cache: yes

- name: htpasswd module
  pip:
   name: passlib
   state: latest

- name: nagiosadmin account
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ nagadmin_pass }}'

- name: apache
  service:
   name: httpd
   state: reloaded

# tasks file for roles/centos/nagios
