---
- name: FTP server on OpenSuse installation
  zypper:
   name: vsftpd
   state: latest

- name: FTP server
  service:
   name: vsftpd
   state: started
   enabled: yes

- name: ftp user
  user:
   name: '{{ user }}'
   password: '{{ ftp_pass }}'

- name: access ssh
  lineinfile:
   path: /etc/ssh/sshd_config
   line: "DenyUsers '{{ user }}'"
  register: successfully_denied

- name: Restarting sshd service
  service:
   name: sshd
   state: restarted
  when: successfully_denied.changed

- name: configuration file
  copy:
   src: /etc/vsftpd.conf
   dest: /etc/vsftpd.conf.default
   remote_src: True

- name: allow ftp
  replace:
   path: /etc/vsftpd.conf
   regexp: 'write_enable=NO'
   replace: 'write_enable=YES'

- name: Enable ls recurse
  replace:
   path: /etc/vsftpd.conf
   regexp: '#ls_recurse_enable=YES'
   replace: 'ls_recurse_enable=YES'

- name: Enable ascii download
  replace:
   path: /etc/vsftpd.conf
   regexp: '#ascii_download_enable=YES'
   replace: 'ascii_download_enable=YES'

- name: Configure ftp file
  lineinfile:
   path: /etc/vsftpd.conf
   line: local_root=/ftp

- name: Restart Vsftpd
  service:
   name: vsftpd
   state: restarted
# tasks file for roles/opensuse/sftp